# Generated by Django 5.2.2 on 2025-06-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('PHN', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('ps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Playground Model',
                'verbose_name_plural': 'Playground Models',
                'ordering': ['-year', 'month', 'surname'],
            },
        ),
    ]
